services:
  # Camera Stream API (Team A2 - Consumer)
  api:
    build: .
    image: v1.0.0-team-camera-api
    container_name: camera-stream-api
    environment:
      - SERVICE_NAME=camera-stream-service
      - SERVICE_VERSION=1.0.0
      - AUTH_TOKEN=lab-token
      - AI_SERVICE_URL=http://ai-vision-provider:8004
      - APP_PORT=8002
      - CAMERA_STREAM_URL=https://camera.labaiotdnu.app/video?key=demo
    depends_on:
      db:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    networks:
      - team-internal
      - class-net
    ports:
      - "8002:8002"
    volumes:
      - snapshots-data:/app/snapshots
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8002/health')"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Database cho Camera Detections
  db:
    image: postgres:15-alpine
    container_name: camera-db
    environment:
      POSTGRES_USER: lab05
      POSTGRES_PASSWORD: lab05pass
      POSTGRES_DB: cameradb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - team-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lab05"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AI Vision Provider (Mock A4)
  ai-service:
    build: .
    image: v1.0.0-team-camera-ai
    container_name: ai-vision-provider
    environment:
      - WEBHOOK_URL=http://camera-stream-api:8002/webhook/detection-completed
      - SNAPSHOT_DIR=/app/snapshots
      - APP_PORT=8004
    command: ["uvicorn", "ai_service.main:app", "--app-dir", "src", "--host", "0.0.0.0", "--port", "8004"]
    volumes:
      - snapshots-data:/app/snapshots
    networks:
      - team-internal
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8004/health')"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  team-internal:
    driver: bridge
  class-net:
    external: true

volumes:
  db-data:
  snapshots-data:
